### ISSUE TITLE
bdelete closes window in some cases

### ISSUE THREAD

**Issue by brukberhane** [Sewdohe/nvim-config#6]
So what I've noticed about this bug is that it often happens only when I opened a folder and not a specific file, If you open a file and then go to open up other files in the tree view, then `bd` works as anticipated. But whenever you run `nvim .` or just open a project from Neovide, then `bd` closes the entire window.

**Comment by Sewdohe** [comment]
So, doing a little bit of research I found this reddit thread: https://www.reddit.com/r/neovim/comments/qutepz/bdelete_closes_neovim_entirely_not_just_the/

we aren't alone in this issue. It has something to do with the file tree. 

I'm thinking we move to cokeline which has built in support for file-tree type buffers: 

https://github.com/noib3/nvim-cokeline

I think it looks better, too!

**Comment by Sewdohe** [comment]
Didn't mean to close, sorry

**Comment by brukberhane** [comment]
> Didn't mean to close, sorry

No problem.

> So, doing a little bit of research I found this reddit thread: https://www.reddit.com/r/neovim/comments/qutepz/bdelete_closes_neovim_entirely_not_just_the/
> 
> we aren't alone in this issue. It has something to do with the file tree.
> 
> I'm thinking we move to cokeline which has built in support for file-tree type buffers:
> 
> https://github.com/noib3/nvim-cokeline
> 
> I think it looks better, too!

Yeah it looks pretty great! Let me know when you've tried it out and if it works well on your config?

**Comment by Sewdohe** [comment]
I will test it tonight and get it configured nice and pretty like for us! Expect commit to fix this later this evening.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by brukberhane** [comment]
I just tried out cokeline. It worked like a charm! Working really great now. We can close this off
